-- Hardening komersial KLAAR: seller portal, sesi aplikasi, rate limit, dan
-- optimistic locking. Migration lama tidak diubah agar riwayat produksi auditabel.

create extension if not exists pgcrypto;

alter table public.databases
  add column if not exists revision bigint not null default 1;

-- Token lisensi dapat berganti setiap perpanjangan, tetapi tenant_key tetap.
-- Baris lama memakai license_code sebagai tenant_key agar kompatibel penuh.
alter table public.licenses add column if not exists tenant_key text;
alter table public.licenses add column if not exists access_token text;
alter table public.licenses add column if not exists contact_email text not null default '';
update public.licenses
set tenant_key = coalesce(nullif(tenant_key, ''), license_code),
    access_token = coalesce(nullif(access_token, ''), license_code)
where tenant_key is null or tenant_key = '' or access_token is null or access_token = '';
alter table public.licenses alter column tenant_key set not null;
alter table public.licenses alter column access_token set not null;
create unique index if not exists licenses_tenant_key_uidx on public.licenses (tenant_key);
create unique index if not exists licenses_access_token_uidx on public.licenses (access_token);
update public.licenses
set plan = 'monthly', updated_at = now()
where lower(coalesce(plan, '')) in ('', 'starter', 'annual', 'yearly');

create table if not exists public.seller_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  role text not null default 'seller' check (role in ('seller', 'owner', 'support')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_orders (
  id uuid primary key default gen_random_uuid(),
  order_id text not null unique,
  school_name text not null,
  buyer_email text not null,
  plan text not null default 'monthly',
  billing_period text not null default 'monthly' check (billing_period = 'monthly'),
  duration_months integer not null default 1 check (duration_months between 1 and 12),
  amount integer not null default 0 check (amount >= 0),
  currency text not null default 'IDR' check (currency = 'IDR'),
  payment_proof text not null default '',
  buyer_notes text not null default '',
  status text not null default 'pending' check (status in ('pending', 'payment_review', 'paid', 'cancelled')),
  license_code text references public.licenses(license_code) on delete set null,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seller_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null default '',
  target_id text not null default '',
  request_fingerprint text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.license_time_grants (
  id uuid primary key default gen_random_uuid(),
  license_code text not null references public.licenses(license_code) on delete cascade,
  grant_type text not null default 'complimentary' check (grant_type in ('complimentary')),
  granted_days integer not null check (granted_days between 1 and 365),
  previous_expires_at timestamptz,
  new_expires_at timestamptz not null,
  reason text not null,
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.app_sessions (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  license_code text not null references public.licenses(license_code) on delete cascade,
  subject_type text not null check (subject_type in ('admin', 'employee')),
  subject_id text not null,
  device_id text not null default '',
  device_name text not null default '',
  user_agent text not null default '',
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.api_rate_limits (
  rate_key text primary key,
  scope text not null,
  attempts integer not null default 0,
  window_started_at timestamptz not null default now(),
  blocked_until timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists store_orders_status_created_idx
  on public.store_orders (status, created_at desc);
create index if not exists store_orders_email_created_idx
  on public.store_orders (buyer_email, created_at desc);
create index if not exists seller_audit_created_idx
  on public.seller_audit_logs (created_at desc);
create index if not exists license_time_grants_tenant_created_idx
  on public.license_time_grants (license_code, created_at desc);
create index if not exists app_sessions_lookup_idx
  on public.app_sessions (license_code, subject_type, subject_id, expires_at desc)
  where revoked_at is null;
create index if not exists app_sessions_expiry_idx
  on public.app_sessions (expires_at)
  where revoked_at is null;
create index if not exists api_rate_limits_updated_idx
  on public.api_rate_limits (updated_at);

-- Satu operasi atomik untuk membatasi brute force dan spam checkout.
create or replace function public.consume_rate_limit(
  p_key text,
  p_scope text,
  p_limit integer,
  p_window_seconds integer,
  p_block_seconds integer
)
returns table(allowed boolean, retry_after_seconds integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row public.api_rate_limits%rowtype;
  now_at timestamptz := clock_timestamp();
  safe_limit integer := greatest(1, least(coalesce(p_limit, 1), 1000));
  safe_window integer := greatest(1, least(coalesce(p_window_seconds, 60), 86400));
  safe_block integer := greatest(1, least(coalesce(p_block_seconds, 300), 86400));
begin
  if coalesce(length(p_key), 0) < 16 or coalesce(length(p_scope), 0) < 1 then
    raise exception 'rate limit key tidak valid';
  end if;

  insert into public.api_rate_limits(rate_key, scope, attempts, window_started_at, updated_at)
  values (p_key, left(p_scope, 80), 0, now_at, now_at)
  on conflict (rate_key) do nothing;

  select * into current_row
  from public.api_rate_limits
  where rate_key = p_key
  for update;

  if current_row.blocked_until is not null and current_row.blocked_until > now_at then
    return query select false, greatest(1, ceil(extract(epoch from (current_row.blocked_until - now_at)))::integer);
    return;
  end if;

  if current_row.window_started_at <= now_at - make_interval(secs => safe_window) then
    current_row.attempts := 0;
    current_row.window_started_at := now_at;
    current_row.blocked_until := null;
  end if;

  current_row.attempts := current_row.attempts + 1;
  if current_row.attempts > safe_limit then
    current_row.blocked_until := now_at + make_interval(secs => safe_block);
  end if;

  update public.api_rate_limits
  set attempts = current_row.attempts,
      window_started_at = current_row.window_started_at,
      blocked_until = current_row.blocked_until,
      updated_at = now_at
  where rate_key = p_key;

  return query select
    current_row.blocked_until is null,
    case when current_row.blocked_until is null then 0
      else greatest(1, ceil(extract(epoch from (current_row.blocked_until - now_at)))::integer)
    end;
end;
$$;

create or replace function public.reset_rate_limit(p_key text)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.api_rate_limits where rate_key = p_key;
$$;

create or replace function public.apply_complimentary_extension(
  p_license_code text,
  p_expected_updated_at timestamptz,
  p_access_token text,
  p_new_expires_at timestamptz,
  p_days integer,
  p_reason text,
  p_actor uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_license public.licenses%rowtype;
begin
  if p_days < 1 or p_days > 365 or length(trim(coalesce(p_reason, ''))) < 5 then
    raise exception 'parameter waktu gratis tidak valid';
  end if;

  select * into current_license
  from public.licenses
  where license_code = p_license_code
  for update;

  if not found or current_license.updated_at is distinct from p_expected_updated_at then
    return false;
  end if;

  update public.licenses
  set access_token = p_access_token,
      expires_at = p_new_expires_at,
      status = 'active',
      plan = 'monthly',
      updated_at = now()
  where license_code = p_license_code;

  insert into public.license_time_grants(
    license_code, grant_type, granted_days, previous_expires_at,
    new_expires_at, reason, granted_by
  ) values (
    p_license_code, 'complimentary', p_days, current_license.expires_at,
    p_new_expires_at, trim(p_reason), p_actor
  );

  return true;
end;
$$;

alter table public.seller_users enable row level security;
alter table public.store_orders enable row level security;
alter table public.seller_audit_logs enable row level security;
alter table public.license_time_grants enable row level security;
alter table public.app_sessions enable row level security;
alter table public.api_rate_limits enable row level security;

revoke all on table public.seller_users from anon, authenticated;
revoke all on table public.store_orders from anon, authenticated;
revoke all on table public.seller_audit_logs from anon, authenticated;
revoke all on table public.license_time_grants from anon, authenticated;
revoke all on table public.app_sessions from anon, authenticated;
revoke all on table public.api_rate_limits from anon, authenticated;
revoke all on function public.consume_rate_limit(text, text, integer, integer, integer) from public, anon, authenticated;
revoke all on function public.reset_rate_limit(text) from public, anon, authenticated;
revoke all on function public.apply_complimentary_extension(text, timestamptz, text, timestamptz, integer, text, uuid) from public, anon, authenticated;
grant execute on function public.consume_rate_limit(text, text, integer, integer, integer) to service_role;
grant execute on function public.reset_rate_limit(text) to service_role;
grant execute on function public.apply_complimentary_extension(text, timestamptz, text, timestamptz, integer, text, uuid) to service_role;

-- Bersihkan data operasional yang sudah tidak berguna tanpa menyentuh data sekolah.
delete from public.app_sessions
where expires_at <= now() or revoked_at is not null and revoked_at <= now() - interval '30 days';
delete from public.api_rate_limits
where updated_at <= now() - interval '7 days';
