-- Klaar production schema baseline.
-- Aman dijalankan berulang: tabel/kolom/index dibuat hanya bila belum ada.

create extension if not exists pgcrypto;

create table if not exists public.licenses (
  license_code text primary key,
  school_name text not null default '',
  school_code text not null default '',
  status text not null default 'active',
  plan text not null default 'starter',
  expires_at timestamptz,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.licenses add column if not exists school_name text not null default '';
alter table public.licenses add column if not exists school_code text not null default '';
alter table public.licenses add column if not exists status text not null default 'active';
alter table public.licenses add column if not exists plan text not null default 'starter';
alter table public.licenses add column if not exists expires_at timestamptz;
alter table public.licenses add column if not exists notes text not null default '';
alter table public.licenses add column if not exists created_at timestamptz not null default now();
alter table public.licenses add column if not exists updated_at timestamptz not null default now();

create table if not exists public.databases (
  license_code text primary key references public.licenses(license_code) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.databases add column if not exists payload jsonb not null default '{}'::jsonb;
alter table public.databases add column if not exists updated_at timestamptz not null default now();

create table if not exists public.attendance_records (
  license_code text not null references public.licenses(license_code) on delete cascade,
  attendance_date date not null,
  employee_id text not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (license_code, attendance_date, employee_id)
);

alter table public.attendance_records add column if not exists payload jsonb not null default '{}'::jsonb;
alter table public.attendance_records add column if not exists updated_at timestamptz not null default now();

create table if not exists public.attendance_requests (
  id text primary key,
  license_code text not null references public.licenses(license_code) on delete cascade,
  employee_id text not null,
  attendance_date date not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.attendance_requests add column if not exists payload jsonb not null default '{}'::jsonb;
alter table public.attendance_requests add column if not exists created_at timestamptz not null default now();
alter table public.attendance_requests add column if not exists updated_at timestamptz not null default now();

create table if not exists public.attendance_selfies (
  id uuid primary key default gen_random_uuid(),
  license_code text not null references public.licenses(license_code) on delete cascade,
  employee_id text not null,
  employee_name text not null default '',
  attendance_date date not null,
  type text not null,
  selfie_url text not null default '',
  storage_path text not null,
  lat double precision,
  lng double precision,
  accuracy double precision,
  location_name text not null default '',
  watermark_text text not null default '',
  file_size_bytes bigint,
  captured_at timestamptz not null default now()
);

alter table public.attendance_selfies add column if not exists employee_name text not null default '';
alter table public.attendance_selfies add column if not exists selfie_url text not null default '';
alter table public.attendance_selfies add column if not exists storage_path text;
alter table public.attendance_selfies add column if not exists lat double precision;
alter table public.attendance_selfies add column if not exists lng double precision;
alter table public.attendance_selfies add column if not exists accuracy double precision;
alter table public.attendance_selfies add column if not exists location_name text not null default '';
alter table public.attendance_selfies add column if not exists watermark_text text not null default '';
alter table public.attendance_selfies add column if not exists file_size_bytes bigint;
alter table public.attendance_selfies add column if not exists captured_at timestamptz not null default now();

create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  action text not null,
  license_code text not null default '',
  message text not null default '',
  created_at timestamptz not null default now()
);

alter table public.logs add column if not exists action text;
alter table public.logs add column if not exists license_code text not null default '';
alter table public.logs add column if not exists message text not null default '';
alter table public.logs add column if not exists created_at timestamptz not null default now();

create index if not exists attendance_records_tenant_date_idx
  on public.attendance_records (license_code, attendance_date desc);
create index if not exists attendance_requests_tenant_employee_idx
  on public.attendance_requests (license_code, employee_id, attendance_date desc);
create index if not exists attendance_selfies_tenant_date_idx
  on public.attendance_selfies (license_code, attendance_date desc, captured_at desc);
create index if not exists logs_tenant_created_idx
  on public.logs (license_code, created_at desc);

-- Semua akses data aplikasi harus melalui Edge Function dengan service-role.
alter table public.licenses enable row level security;
alter table public.databases enable row level security;
alter table public.attendance_records enable row level security;
alter table public.attendance_requests enable row level security;
alter table public.attendance_selfies enable row level security;
alter table public.logs enable row level security;

revoke all on table public.licenses from anon, authenticated;
revoke all on table public.databases from anon, authenticated;
revoke all on table public.attendance_records from anon, authenticated;
revoke all on table public.attendance_requests from anon, authenticated;
revoke all on table public.attendance_selfies from anon, authenticated;
revoke all on table public.logs from anon, authenticated;

-- Bucket foto wajib private. Service-role Edge Function tetap dapat upload/read.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('selfies', 'selfies', false, 3145728, array['image/jpeg'])
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- Tidak ada policy untuk anon/authenticated: foto hanya bisa dibaca melalui signed URL.
